const OnboardingData = [
    {
      name: "John Doe",
      dob: "15/01/1990",
      phoneNumber: "+1234567890",
      email: "john.doe@example.com",
      type: "Salaried",
      emergency: "9988776655",
      contact: "Father",
      bloodGroup: "O+",
      address: "123, Main Street, Springfield",
      idProof: "",
      drivingLicense: "",
      vehicle: "",
      action: "Active",
    },
    {
      name: "Jane Smith",
      dob: "10/11/1985",
      phoneNumber: "+9876543210",
      email: "jane.smith@example.com",
      type: "Salaried",
      emergency: "9988776655",
      contact: "Father",
      bloodGroup: "A-",
      address: "456, Elm Street, Shelbyville",
      idProof: "",
      drivingLicense: "",
      vehicle: "",
      action: "Inactive",
    },
   { name: "John Doe",
      dob: "15/01/1990",
      phoneNumber: "+1234567890",
      email: "john.doe@example.com",
      type: "Salaried",
      emergency: "9988776655",
      contact: "Father",
      bloodGroup: "O+",
      address: "123, Main Street, Springfield",
      idProof: "",
      drivingLicense: "",
      vehicle: "",
    },
    { name: "John Doe",
        dob: "15/01/1990",
        phoneNumber: "+1234567890",
        email: "john.doe@example.com",
        type: "Salaried",
        emergency: "9988776655",
        contact: "Father",
        bloodGroup: "O+",
        address: "123, Main Street, Springfield",
        idProof: "",
        drivingLicense: "",
        vehicle: "",
      },
      { name: "John Doe",
        dob: "15/01/1990",
        phoneNumber: "+1234567890",
        email: "john.doe@example.com",
        type: "Salaried",
        emergency: "9988776655",
        contact: "Father",
        bloodGroup: "O+",
        address: "123, Main Street, Springfield",
        idProof: "",
        drivingLicense: "",
        vehicle: "",
      },
      { name: "John Doe",
        dob: "15/01/1990",
        phoneNumber: "+1234567890",
        email: "john.doe@example.com",
        type: "Salaried",
        emergency: "9988776655",
        contact: "Father",
        bloodGroup: "O+",
        address: "123, Main Street, Springfield",
        idProof: "",
        drivingLicense: "",
        vehicle: "",
      },
      { name: "John Doe",
        dob: "15/01/1990",
        phoneNumber: "+1234567890",
        email: "john.doe@example.com",
        type: "Salaried",
        emergency: "9988776655",
        contact: "Father",
        bloodGroup: "O+",
        address: "123, Main Street, Springfield",
        idProof: "",
        drivingLicense: "",
        vehicle: "",
      },
      { name: "John Doe",
        dob: "15/01/1990",
        phoneNumber: "+1234567890",
        email: "john.doe@example.com",
        type: "Salaried",
        emergency: "9988776655",
        contact: "Father",
        bloodGroup: "O+",
        address: "123, Main Street, Springfield",
        idProof: "",
        drivingLicense: "",
        vehicle: "",
      },
      { name: "John Doe",
        dob: "15/01/1990",
        phoneNumber: "+1234567890",
        email: "john.doe@example.com",
        type: "Salaried",
        emergency: "9988776655",
        contact: "Father",
        bloodGroup: "O+",
        address: "123, Main Street, Springfield",
        idProof: "",
        drivingLicense: "",
        vehicle: "",
      },
      { name: "John Doe",
        dob: "15/01/1990",
        phoneNumber: "+1234567890",
        email: "john.doe@example.com",
        type: "Salaried",
        emergency: "9988776655",
        contact: "Father",
        bloodGroup: "O+",
        address: "123, Main Street, Springfield",
        idProof: "",
        drivingLicense: "",
        vehicle: "",
      },
      { name: "John Doe",
        dob: "15/01/1990",
        phoneNumber: "+1234567890",
        email: "john.doe@example.com",
        type: "Salaried",
        emergency: "9988776655",
        contact: "Father",
        bloodGroup: "O+",
        address: "123, Main Street, Springfield",
        idProof: "",
        drivingLicense: "",
        vehicle: "",
      }
    // Additional records can be added as needed
  ];
  
  export default OnboardingData;
  